import Head from 'next/head'
import { Inter } from '@next/font/google';
import NavBar from '@/Components/NavBar/NavBar';
import Parts from '@/Components/OtherParts/Parts';
import Footer from '@/Components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Online Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.webp" />
      </Head>
      <div>
        <NavBar></NavBar>
        <Parts></Parts>
        <Footer></Footer>
      </div>
    </>
  )
}
